[package]
name = "kontemplate"
version = "0.1.0"
authors = ["Vincent Ambo <tazjin@gmail.com>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
error-chain = "0.11.0"
serde_yaml = "0.7"


[dependencies.liquid]
version = "0.10.1"
features = [ "serde" ]
